name = "prnt"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./"

[[d1_databases]]
binding = "DB"
database_name = "prnt-db"
database_id = "f4974a76-0ae1-4447-8d0a-e268f1dbd4f8"  # Replace with your D1 database ID
